
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.json.JSONArray;
import project_sanwa_new.Alert;
import project_sanwa_new.Area;
import project_sanwa_new.DBArea;
import project_sanwa_new.DBDetail;
import project_sanwa_new.DBRoom;
import project_sanwa_new.DataAlert;
import project_sanwa_new.Database;
import project_sanwa_new.ListAlert;
import project_sanwa_new.Sanwa;
import project_sanwa_new.SelectComboBox;
import project_sanwa_new.StateCheck;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yotsathon
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    static ViewTable va;
    static ViewTable viewTable;

    static Home home;
    static ImportData importData;
    static Manages manage;
    static Reporting report;
    static Setting setting;
    static UpdateProgram updateProgram;
    static SupportUser supportUser;

    public static List<DataAlert> listDataAlert;
    public static List<Alert> alert;
    static ListAlert listAlert;
    static Map<String, String> startDateTime;
    static String dateTime;
    Menu menuHome;
    Menu menuViewDataTable;
    Menu menuManage;
    Menu menuView;
    Menu menuReport;
    Menu menuSetting;
    Menu menuUpdateProgram;
    Menu menuSupportUser;
    JPanel topArea;
    JPanel menu;
    JPanel content;

    static JProgressBar progressBar;
    SiteTabList siteTabList;

    public Main() {
        initComponents();

        this.setBackground(new Color(243, 242, 243));
        this.setPreferredSize(new Dimension(900, 800));
        content = new JPanel();
        content.setBackground(new Color(243, 242, 243));
        home = new Home();
        viewTable = new ViewTable();

        manage = new Manages();
        setting = new Setting();
        progressBar = new JProgressBar();
        progressBar.setFont(new java.awt.Font("Century Gothic", 0, 10));
        progressBar.setStringPainted(true);
        progressBar.setBackground(new Color(255, 100, 100));

        progressBar.setForeground(Color.blue);

        menu = new JPanel();
        menu.setBackground(new Color(243, 242, 243));

//        menuHome = new Menu("home", "/project_sanwa_new/img/Mangement_48px_1.png", content, home);
//        menuViewDataTable = new Menu("DATA TABLE", "/project_sanwa_new/img/Organization_64px.png", content, viewTable);
        menuManage = new Menu("Management", "/project_sanwa_new/img/Mangement_48px_1.png", content, manage);
        menuReport = new Menu("Reporting", "/project_sanwa_new/img/Reporting_48px.png", content, report);
        menuSetting = new Menu("Setting", "/project_sanwa_new/img/Setting_48px.png", content, setting);
        menuUpdateProgram = new Menu("Update", "/project_sanwa_new/img/Synchronize_48px.png", content, updateProgram);
        menuSupportUser = new Menu("Support", "/project_sanwa_new/img/Online Support_48px.png", content, supportUser);

        menu.add(menuManage);
        menu.add(menuReport);
        menu.add(menuSetting);
        menu.add(menuUpdateProgram);
        menu.add(menuSupportUser);
        // menu.add(menuHome);
        //menu.add(menuViewDataTable);
        // menu.add(menuView);

        topArea = new JPanel();
        topArea.setLayout(new BoxLayout(topArea, BoxLayout.Y_AXIS));
        topArea.add(menu);
        topArea.add(progressBar);

        siteTabList = new SiteTabList();

        content.add(siteTabList);
        //content.add(tab);
        add(topArea, BorderLayout.PAGE_START); //0, 0, 100, 768
        add(content, BorderLayout.CENTER); //100, 0, 945, 768

        importData = new ImportData();

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setMinimumSize(new java.awt.Dimension(1024, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void loadData() {
        StateCheck sc = new StateCheck();
        sc.state = false;
        Runnable runnable2 = new Runnable() {
            public void run() {
                synchronized (sc) {

                    try {
                        sc.wait();
                        getDataToAlert();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }
        };
        new Thread(runnable2).start();

        Runnable runnable = new Runnable() {
            public void run() {
                synchronized (sc) {
                    try {

                        getRoomDetailFromServer();
//                        Sanwa sw = new Sanwa();
//                        sw.getStartDateTime();
                        sc.state = true;
                        sc.notifyAll();

                    } catch (IOException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }
        };
        new Thread(runnable).start();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new Main().setVisible(true);
        Timer time = new Timer();
        time.schedule(new TimerTask() {
            public void run() {
                Database db = new Database();
                db.connect();
                if (db.getStatusStartProgram()) {
                    loadData();
                }
                db.close();
            }

        }, 0, 1000 * 5000);

    }

    public static void getRoomDetailFromServer() throws IOException, SQLException {
        DBRoom dbR = new DBRoom();
        DBDetail dbD = new DBDetail();
        dbR.connect();
        dbD.connect();

        Sanwa sw = new Sanwa();
        Map<String, String> startDateTime = sw.getCurentDateTime();
        //ResultSet rs = dbR.selectRoomByBuildingFloor(null, null);

        float progress = 1;
        URL url;
        BufferedReader in;
        JSONArray jsonArray;
        dateTime = startDateTime.get("dateTimeLocal").toString();
        url = new URL("http://dragoservices.azurewebsites.net/api/DragoServices/MeterRecord?s=" + startDateTime.get("dateTimeLocal") + "%2B0700");
       // url = new URL("http://dragoservices.azurewebsites.net/api/DragoServices/MeterRecord?s=" + midNightDateTime.get("dateTimeServer") + "%2B0700");
        in = new BufferedReader(new InputStreamReader(url.openStream()));
        String line = in.readLine();
        if (!"[]".equals(line)) {

            jsonArray = new JSONArray(line);
            float count = jsonArray.length();
            for (int i = 0; i < jsonArray.length(); i++) {
                //String t = jsonArray.getJSONObject(i).getJSONArray("records").getJSONObject(0).get("t").toString();
                String mBusID = jsonArray.getJSONObject(i).get("mBusID").toString();
                String dragoConnexID = jsonArray.getJSONObject(i).get("dragoConnexID").toString();
                dragoConnexID = dragoConnexID.substring(2);
                String wFl = jsonArray.getJSONObject(i).getJSONArray("records").getJSONObject(0).get("wFl").toString();
                int rs = dbR.selectIDBymBusIDDateTime(dragoConnexID, mBusID, dateTime);
                if (rs == 0) {
                    ResultSet roomID = dbR.selectRoomIDBymBusID(dragoConnexID, mBusID);
                    if (roomID.next()) {
                        dbD.insertDetailRoomWater(roomID.getString("room_ID").toString(), dateTime, wFl, jsonArray.getJSONObject(i).getJSONArray("records").getJSONObject(0).get("wFw").toString(), jsonArray.getJSONObject(i).getJSONArray("records").getJSONObject(0).get("wRv").toString(), jsonArray.getJSONObject(i).getJSONArray("records").getJSONObject(0).get("wVo").toString());
                        //System.out.println(roomID.getString("room_ID").toString());
                    }

                }
                float percen = (progress / count) * 100;
                progressBar.setString(Math.round(percen) + "%");
                progressBar.setValue(Math.round(percen));
                progress++;

            }

        }
        dbD.close();
        dbR.close();
    }

    public static void getRoomDetailFromServer2() throws IOException, SQLException {
        DBRoom dbR = new DBRoom();
        DBDetail dbD = new DBDetail();
        dbR.connect();
        dbD.connect();

        Sanwa sw = new Sanwa();
        Map<String, String> startDateTime = sw.getCurentDateTime();
        //ResultSet rs = dbR.selectRoomByBuildingFloor(null, null);

        float progress = 1;
        URL url;
        BufferedReader in;
        JSONArray jsonArray;
        dateTime = startDateTime.get("dateTimeLocal").toString();

//        try {
        String date = dateTime.substring(0, 10);
        url = new URL("http://dragoservices.azurewebsites.net/api/DragoServices/MeterRecord?s=" + date+"T00:00:00" + "%2B0700");
        in = new BufferedReader(new InputStreamReader(url.openStream()));
        String line = in.readLine();
        if (!"[]".equals(line)) {

            jsonArray = new JSONArray(line);
            float count = jsonArray.length();
            for (int i = 0; i < jsonArray.length(); i++) {
                String mBusID = jsonArray.getJSONObject(i).get("mBusID").toString();
                String dragoConnexID = jsonArray.getJSONObject(i).get("dragoConnexID").toString();
                dragoConnexID = dragoConnexID.substring(2);

                JSONArray subMBus = jsonArray.getJSONObject(i).getJSONArray("records");
                for (int j = 0; j < subMBus.length(); j++) {
                    dateTime = subMBus.getJSONObject(j).getString("t").toString();
                    String wFl = subMBus.getJSONObject(j).get("wFl").toString();
                    int rs = dbR.selectIDBymBusIDDateTime(dragoConnexID, mBusID, dateTime);
                    if (rs == 0) {
                        ResultSet roomID = dbR.selectRoomIDBymBusID(dragoConnexID, mBusID);
                        if (roomID.next()) {
                            dbD.insertDetailRoomWater(roomID.getString("room_ID").toString(), dateTime, wFl, subMBus.getJSONObject(j).get("wFw").toString(), subMBus.getJSONObject(j).get("wRv").toString(), subMBus.getJSONObject(j).get("wVo").toString());
                            //System.out.println(roomID.getString("room_ID").toString());
                        }

                    }

                }

                float percen = (progress / count) * 100;
                progressBar.setString(Math.round(percen) + "%");
                progressBar.setValue(Math.round(percen));
                progress++;

            }

        }
        dbD.close();
        dbR.close();
    }

    public static void getDataToAlert() {
        DBRoom dbR = new DBRoom();
        DBDetail dbD = new DBDetail();
        dbR.connect();
        dbD.connect();
        Sanwa sw = new Sanwa();

        listAlert = new ListAlert();
        try {
            ResultSet allRoom = dbR.selectAllRoom();
            while (allRoom.next()) {
                ResultSet alert = dbD.selectWaterDetailToAlert(allRoom.getString("room_ID"), dateTime);
                if (alert.next()) {
                    String date = dateTime.substring(0, 10);
                    String time = dateTime.substring(11);
                    //listAlert.setListAlert(alert.getString("siteName"), alert.getString("areaName"), alert.getString("dragoConnexName"), alert.getString("roomNumber"), alert.getString("w_mBusID"), alert.getString("w_high_treshold"), alert.getString("wFw"), date, time);

                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ViewTable.class.getName()).log(Level.SEVERE, null, ex);
        }

        dbR.close();
        dbD.close();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
